### ISSUE TITLE
Define GameField

### ISSUE THREAD

**Issue by Sikredo** [SE2-Gwent/Gwent#11]
As a Developer I want to see a JSON representation of the game field.

Acceptance Criteria:

- JSON Document with an initial gameObject is created
- 2nd JSON document with a runnning gameObject is created
- Java Classes are implemented

**Comment by raphaelseher** [comment]
We should also define the Gwent rules for the GameField here: https://github.com/SE2-Gwent/Gwent/wiki/Gamelogic

**Comment by Sikredo** [comment]
![image](https://user-images.githubusercontent.com/34310772/163234422-741776fc-057b-400f-914d-25c96f9212fc.png)
